{
	"name": "Internetradio",
	"speakableName": "Listen to the radio",
	"version": "0.0.1",
	"icon": "fab fa-battle-net",
	"category": "entertainment",
	"author": "lazzaAU",
	"maintainers": [],
	"desc": "Listen to internet radio stations",
	"aliceMinVersion": "1.0.0-b3",
	"pipRequirements": [
		"mpd"
	],
	"systemRequirements": [
		"mpd,mpc"
	],
	"conditions": {
		"lang": [
			"en"
		],
		"online": true
	}
}