{
	"name": "InternetRadio",
	"speakableName": "Listen to the radio",
	"version": "1.0.0",
	"icon": "fas fa-radio",
	"category": "entertainment",
	"author": "lazza",
	"maintainers": [],
	"desc": "Listen to internet radio stations",
	"aliceMinVersion": "1.0.0-b3",
	"pipRequirements": [],
	"systemRequirements": [
		"mpd",
		"mpc"
	],
	"conditions": {
		"lang": [
			"en",
			"de"
		],
		"online": true
	}
}
